// <auto-generated />
using System;
using GorevTakipSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GorevTakipSistemi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601083416_InitialCreate_SQLite")]
    partial class InitialCreate_SQLite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("GorevTakipSistemi.Models.Bildirim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OkunduMu")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Bildirimler");
                });

            modelBuilder.Entity("GorevTakipSistemi.Models.DestekMesaji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cevap")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCevaplandi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("DestekMesajlari");
                });

            modelBuilder.Entity("GorevTakipSistemi.Models.Ekip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KurucuId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KurulusTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KurucuId");

                    b.ToTable("Ekipler");
                });

            modelBuilder.Entity("GorevTakipSistemi.Models.EkipDavet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AliciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DavetTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EkipId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GonderenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AliciId");

                    b.HasIndex("EkipId");

                    b.HasIndex("GonderenId");

                    b.ToTable("EkipDavetleri");
                });

            modelBuilder.Entity("GorevTakipSistemi.Models.EkipUyesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EkipId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KatilmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EkipId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("EkipUyeleri");
                });

            modelBuilder.Entity("GorevTakipSistemi.Models.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AtayanKullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DurumAktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EkipId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GorevAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Oncelik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AtayanKullaniciId");

                    b.HasIndex("EkipId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("GorevTakipSistemi.Models.GorevTamamlama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GorevId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TamamlamaTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("GorevTamamlamalari");
                });

            modelBuilder.Entity("GorevTakipSistemi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BanBitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("BanNedeni")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("KvkkOnay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfilResmi")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResetToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResetTokenBitisSuresi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("GorevTakipSistemi.Models.SistemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAdresi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("YapilanIslem")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SistemLoglari");
                });

            modelBuilder.Entity("GorevTakipSistemi.Models.Bildirim", b =>
                {
                    b.HasOne("GorevTakipSistemi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("GorevTakipSistemi.Models.DestekMesaji", b =>
                {
                    b.HasOne("GorevTakipSistemi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("GorevTakipSistemi.Models.Ekip", b =>
                {
                    b.HasOne("GorevTakipSistemi.Models.Kullanici", "Kurucu")
                        .WithMany()
                        .HasForeignKey("KurucuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurucu");
                });

            modelBuilder.Entity("GorevTakipSistemi.Models.EkipDavet", b =>
                {
                    b.HasOne("GorevTakipSistemi.Models.Kullanici", "Alici")
                        .WithMany()
                        .HasForeignKey("AliciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GorevTakipSistemi.Models.Ekip", "Ekip")
                        .WithMany("Davetler")
                        .HasForeignKey("EkipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GorevTakipSistemi.Models.Kullanici", "Gonderen")
                        .WithMany()
                        .HasForeignKey("GonderenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alici");

                    b.Navigation("Ekip");

                    b.Navigation("Gonderen");
                });

            modelBuilder.Entity("GorevTakipSistemi.Models.EkipUyesi", b =>
                {
                    b.HasOne("GorevTakipSistemi.Models.Ekip", "Ekip")
                        .WithMany("Uyeler")
                        .HasForeignKey("EkipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GorevTakipSistemi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ekip");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("GorevTakipSistemi.Models.Gorev", b =>
                {
                    b.HasOne("GorevTakipSistemi.Models.Kullanici", "AtayanKullanici")
                        .WithMany()
                        .HasForeignKey("AtayanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GorevTakipSistemi.Models.Ekip", "Ekip")
                        .WithMany("Gorevler")
                        .HasForeignKey("EkipId");

                    b.HasOne("GorevTakipSistemi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtayanKullanici");

                    b.Navigation("Ekip");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("GorevTakipSistemi.Models.GorevTamamlama", b =>
                {
                    b.HasOne("GorevTakipSistemi.Models.Gorev", "Gorev")
                        .WithMany("Tamamlamalar")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GorevTakipSistemi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gorev");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("GorevTakipSistemi.Models.Ekip", b =>
                {
                    b.Navigation("Davetler");

                    b.Navigation("Gorevler");

                    b.Navigation("Uyeler");
                });

            modelBuilder.Entity("GorevTakipSistemi.Models.Gorev", b =>
                {
                    b.Navigation("Tamamlamalar");
                });
#pragma warning restore 612, 618
        }
    }
}
